server:
  port: 8011
spring:
  application:
    name: server-01
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://localhost:3308/yyds?nullCatalogMeansCurrent=true&serverTimezone=UTC
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #s设置控制台打印sql语句
    cache-enabled: false
    call-setters-on-nulls: true
  type-aliases-package: com.yf.cn.entity  #配置包别名，不同的包别名之间用，分开
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
